// GSLabs_130220/_REACT_/practiceProj/src/server/Server.component.js
import React, {Component} from 'react';
class Server extends Component{
    name = 'Andromeda';
    status = true;
    constructor(props){
        super(props);
    }
    render(){
        let {serverName, serverStatus} = this.props;
        return <li>Server name: {serverName || this.name}. Server status: {(serverStatus && this.status)?'Online':'Offline'}</li>
    }
 }
 export default Server;

// GSLabs_130220/practice-proj/src/app/Server/Server.component.ts
import {Component} from '@angular/core';

@Component({
    selector:'app-server',
    templateUrl: './Server.template.html'
})
export class ServerComponent {
    status = 'Offline';
    name="Andromeda";
    constructor(){
        let test = Math.random();
        if(test>.5)
            this.status = "Online";
    }
    getStyle(){
        return {
            border: `1px solid ${this.status==='Online'?'green':'red'}`
        }
    }
}
