// GSLabs_130220/practice-proj/src_05/app/header/header.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  @Output() routeChanged = new EventEmitter<{route: number}>();
  constructor() { }
  changeRoute(route){
    console.log(route);
    this.routeChanged.emit({route: route})
  }

  ngOnInit(): void {
  }

}

<div fxLayout="row" fxLayoutAlign="space-between" class="header">
    <div fxFlex="80%">
        <div fxLayout="row" fxLayoutAlign="start" class="left-menu">
            <div fxFlex="10%" class="menu-item" (click)="changeRoute(0)">Home</div>
            <div fxFlex="10%" (click)="changeRoute(1)" class="menu-item">Coaches</div>
        </div>
    </div>    
    <div fxFlex="20%" class="menu-item" (click)="changeRoute(2)">Signin</div>
</div>

// GSLabs_130220/_REACT_/courseProj/src/header/header.component.js
import React, {Component} from 'react';
import Grid from '@material-ui/core/Grid';
import Styles from './header.style';
import {NavLink} from 'react-router-dom'
class Header extends Component{
    constructor(props){
        super(props);
        
    }
    render(){
        console.log(this.props);
        return (
            <Grid container direction="row" justify="space-between" style={Styles.headerContainer}>
                <Grid item xs={8}>
                    <Grid container direction="row" justify="flex-start">
                        <Grid item xs={2} style={Styles.menuItem}>
                            <NavLink exact to="/" activeClassName="activeLink">Home</NavLink>
                        </Grid>
                        <Grid item xs={2} style={Styles.menuItem}>
                            <NavLink to="/coaches" activeClassName="activeLink">Coaches</NavLink>
                        </Grid>
                    </Grid>
                </Grid>
                <Grid item xs={4} style={Styles.menuItem}>
                    <NavLink to="/signin" activeClassName="activeLink">Signin</NavLink>
                </Grid>
            </Grid>
        )
    }
}
export default Header;
