// GSLabs_130220/practice-proj/src/app/home/home.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import {LoggingService} from '../logger-service';
import {ServersComponent} from '../servers/servers.component'
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  @Output() onRouteChange = new EventEmitter<{route: number}>();
  constructor() { 
  }

  ngOnInit(): void {
    
  }
  changeRoute(route){
    this.onRouteChange.emit({route: route})
  }
}

<div class="homeContainer" fxLayout="column" fxLayoutAlign="center start">
    <div fxFlex="20%" class="homeContent">
        <h1>Keep it simple silly</h1>
        <p>GetSetGo is an online fitness company that is on a quest to introduce simplicity to nutrition and healthy living.</p>
        <div><button mat-raised-button color="primary" (click)="changeRoute(2)">Get started</button></div>
        <!-- <p highlightgreen>Yo mate!</p>
        <p appBetterHighlightDirective [defaultColor] = "'yellow'" [highlightColor] = "'blue'">Yo mate!</p>  -->
    </div>
    <!-- <app-servers></app-servers> -->
</div>

// GSLabs_130220/_REACT_/courseProj/src/home/home.component.js
import React, {Component} from 'react';
import Grid from '@material-ui/core/Grid';
import {getHt} from '../services';
import Button from '@material-ui/core/Button';

let docHt = getHt()-50;
class Home extends Component{
    render(){
        return (
        <Grid container style={{height: docHt, backgroundColor: '#ccc'}} direction="row" justify="flex-start" alignItems="center">
            <Grid item style={{marginLeft: '100px', textAlign: 'left'}} xs={3}>
                <h1>Keep it simple silly!</h1>
                <p>GetSetGo is an online fitness company that is on a quest to introduce simplicity to nutrition and healthy living.</p>
                <div>
                <Button variant="contained" color="primary">
                    Get Started
                </Button>
                </div>
            </Grid>
        </Grid>
        )
    }
}
export default Home;
