// _ANGULAR_LOWES_/Live_class/concepts/JSConcepts/serverApp/src/app/server-list/Server/server.component.ts
import {Component} from '@angular/core';
@Component({
    selector: 'app-server',
    templateUrl: './server.template.html'
})
export class Server{
    serverStatus = 'online';
    constructor(){
        let status = 10*Math.random();
        this.serverStatus = status>=5?'online':'offline';
    }
}

// GSLabs_130220/_REACT_/practiceProj/src/server/Server.component.js
import React, {Component} from 'react';
class Server extends Component{
    name = 'Andromeda';
    status = true;
    constructor(props){
        super(props);
    }
    render(){
        let {serverName, serverStatus} = this.props;
        return <li>Server name: {serverName || this.name}. Server status: {(serverStatus && this.status)?'Online':'Offline'}</li>
    }
 }
 export default Server;
